spring.datasource.url=jdbc:postgresql://localhost:5432/escuela_juridica
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

logging.level.pe.edu.utp.escuela.app=DEBUG
