spring.datasource.url=jdbc:postgresql://159.198.40.207:5432/aulavirtual_pg
spring.datasource.username=aulavirtual_pguser
spring.datasource.password=LaUztdNfEI3FZFMT4gpol/rblMOEJN+7
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

logging.level.pe.edu.utp.escuela.app=DEBUG
